/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is normally generated by Next.js, but is included here so the
// repository reads as a complete TypeScript-ready App Router project.
